# Generated by Django 3.1.2 on 2020-10-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poste_date',
            new_name='posted_date',
        ),
    ]
